version: '3.3'

services:
  mongosse:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: exampleroot
    # volumes:
    #   - './data:/data/db'

  
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: exampleroot
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/